spring.application.name=Trustra
server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

trustra.scheduling.recalculation.enabled=true
trustra.scheduling.recalculation.fixed-rate-ms=5000
trustra.frontend.origin=https://trustra.antiz.xyz
