spring.application.name=Trustra

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=antiz
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

trustra.scheduling.recalculation.enabled=true
trustra.scheduling.recalculation.fixed-rate-ms=5000
trustra.frontend.origin=${TRUSTRA_FRONTEND_ORIGIN:http://localhost:3000}

